# Reference: https://cloud.google.com/build/docs/build-config-file-schema?authuser=3&_gl=1*o1g5jx*_ga*OTcyMTM3Njc0LjE3NTQ1MjczNjU.*_ga_WH2QY8WWF5*czE3NTQ2NjIzNzEkbzI4JGcxJHQxNzU0NjYzODQxJGoyMSRsMCRoMA..

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'chainlit.Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/llm-data-analysis-playground',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/llm-data-analysis-playground'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'llm-data-analysis-playground',
      '--image', 'gcr.io/$PROJECT_ID/llm-data-analysis-playground',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/llm-data-analysis-playground'

options:
  logging: CLOUD_LOGGING_ONLY